on: push
jobs:
  build:
    name: generate_exe
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4
    - name: install_dependencies
      run: |
        python -m pip install -r requirements.txt
    - name: generate_exe
      run: |
        pyinstaller -F -w client.py
        pyinstaller -F -w server.py
    - name: upload_client_artifacts
      uses: actions/upload-artifact@v4
      with:
        name: njhchat_client
        path: dist/client.exe
    - name: upload_server_artifacts
      uses: actions/upload-artifact@v4
      with:
        name: njhchat_server
        path: dist/server.exe