on: push
jobs:
  build:
    name: Build
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4
    - name: install_dependencies
      run: |
        python -m pip install toml
        python -m pip install pyinstaller
        python -m pip install pycryptodome
        pyinstaller -F -w client.py
        pyinstaller -F -w server.py
    - name: upload_artifacts
      uses: actions/upload-artifact@v4
      with:
        name: njhchat_client
        path: dist/client.exe
    - name: upload_artifacts
      uses: actions/upload-artifact@v4
      with:
        name: njhchat_server
        path: dist/server.exe